FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy project files
COPY frontend/ .

# Start development server
CMD ["npm", "run", "dev", "--", "--host"]