# Generated by Django 5.1.5 on 2025-01-24 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdata',
            options={'ordering': ['-date'], 'verbose_name': 'Biometric Data', 'verbose_name_plural': 'Biometric Data'},
        ),
        migrations.AlterUniqueTogether(
            name='biometricdata',
            unique_together={('athlete', 'date')},
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body fat percentage', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='blood_pressure_diastolic',
            field=models.IntegerField(default=80, help_text='Diastolic blood pressure', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(130)]),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='blood_pressure_systolic',
            field=models.IntegerField(default=120, help_text='Systolic blood pressure', validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='height',
            field=models.DecimalField(decimal_places=2, default=170.0, help_text='Height in cm', max_digits=5, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='hrv',
            field=models.IntegerField(blank=True, help_text='Heart Rate Variability', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='resting_heart_rate',
            field=models.IntegerField(default=60, help_text='Beats per minute', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='sleep_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours of sleep', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='stress_level',
            field=models.IntegerField(default=5, help_text='Stress level from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Weight in kg', max_digits=5, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='body_fat',
        ),
    ]
