# Generated by Django 5.1.5 on 2025-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebiometricdata',
            name='source',
            field=models.CharField(default='garmin', max_length=20),
        ),
    ]
