# Generated by Django 5.1.5 on 2025-03-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corebiometricdata',
            name='start_time',
        ),
    ]
