# Generated by Django 5.1.5 on 2025-01-24 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='athlete',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='hrv',
            field=models.IntegerField(blank=True, help_text='Heart Rate Variability', null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='stress_level',
            field=models.IntegerField(blank=True, help_text='Stress level from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='workoutdata',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutdata',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workoutdata',
            name='workout_type',
            field=models.CharField(choices=[('STRENGTH', 'Strength Training'), ('CARDIO', 'Cardio'), ('RECOVERY', 'Recovery'), ('SKILLS', 'Skills Training'), ('MATCH', 'Match'), ('TEAM_PRACTICE', 'Team Practice')], max_length=20),
        ),
        migrations.CreateModel(
            name='InjuryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('injury_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=10)),
                ('description', models.TextField()),
                ('treatment_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='core.athlete')),
            ],
        ),
    ]
