# Generated by Django 5.1.5 on 2025-03-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_corebiometricdata_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebiometricdata',
            name='average_heart_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='corebiometricdata',
            name='birthdate',
            field=models.DateField(default='<function now at 0x000001CF9705A7A0>'),
        ),
        migrations.AlterField(
            model_name='corebiometricdata',
            name='created_at',
            field=models.DateTimeField(default='<function now at 0x000001CF9705A7A0>'),
        ),
    ]
