# Generated by Django 5.1.5 on 2025-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corebiometricdata_average_heart_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebiometricdata',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corebiometricdata',
            name='created_at',
            field=models.DateTimeField(default='2025-03-05 19:26:40.677761+00:00'),
        ),
    ]
