# Generated by Django 5.1.5 on 2025-01-28 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_oauthtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdata',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='body_fat_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='hrv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='resting_heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='sleep_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
