# Generated by Django 5.1.5 on 2025-02-15 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_garmincredentials_whoopcredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corebiometricdata',
            name='heart_rate_values',
        ),
        migrations.RemoveField(
            model_name='corebiometricdata',
            name='steps',
        ),
        migrations.AlterField(
            model_name='corebiometricdata',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_data', to='core.athlete'),
        ),
    ]
