# Generated by Django 5.1.5 on 2025-03-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_corebiometricdata_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebiometricdata',
            name='created_at',
            field=models.DateTimeField(default='2025-03-06 18:13:31.815169+00:00'),
        ),
    ]
