# Generated by Django 5.1.5 on 2025-01-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_biometricdata_athlete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='blood_pressure_diastolic',
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='blood_pressure_systolic',
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='height',
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='avg_heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='awake_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='calories_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='calories_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='deep_sleep',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='distance_meters',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='intensity_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='light_sleep',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='max_heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='recovery_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='rem_sleep',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='sleep_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='stress_level',
            field=models.IntegerField(default=0),
        ),
    ]
