# Generated by Django 5.1.5 on 2025-02-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_corebiometricdata_heart_rate_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmincredentials',
            name='profile_type',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
