# Generated by Django 5.1.5 on 2025-02-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_garmincredentials_profile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corebiometricdata',
            old_name='awake_sleep',
            new_name='awake_seconds',
        ),
        migrations.RenameField(
            model_name='corebiometricdata',
            old_name='stress_duration',
            new_name='stress_duration_seconds',
        ),
        migrations.RenameField(
            model_name='corebiometricdata',
            old_name='sleep_time_seconds',
            new_name='total_sleep_seconds',
        ),
    ]
