# Generated by Django 5.1.5 on 2025-01-28 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_biometricdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='biometricdata',
            index=models.Index(fields=['-date'], name='core_biomet_date_511532_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdata',
            index=models.Index(fields=['athlete', '-date'], name='core_biomet_athlete_7471e2_idx'),
        ),
    ]
