# Generated by Django 5.1.5 on 2025-02-15 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_awake_sleep_corebiometricdata_awake_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corebiometricdata',
            name='sleep_body_battery',
        ),
        migrations.RemoveField(
            model_name='corebiometricdata',
            name='sleep_heart_rate',
        ),
        migrations.RemoveField(
            model_name='corebiometricdata',
            name='sleep_stress',
        ),
        migrations.CreateModel(
            name='CoreBiometricTimeSeries',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('sleep_heart_rate', models.JSONField(default=list)),
                ('sleep_stress', models.JSONField(default=list)),
                ('sleep_body_battery', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_biometric_time_series',
                'indexes': [models.Index(fields=['id'], name='core_biomet_id_3be53c_idx')],
            },
        ),
    ]
