# Generated by Django 5.1.5 on 2025-01-30 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_biometricdata_created_at_biometricdata_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBiometricData',
            fields=[
                ('uuid', models.UUIDField(editable=False, help_text="UUID must match the athlete's user.id from core_user table", primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sleep_hours', models.FloatField(default=0)),
                ('deep_sleep', models.FloatField(default=0)),
                ('light_sleep', models.FloatField(default=0)),
                ('rem_sleep', models.FloatField(default=0)),
                ('awake_time', models.FloatField(default=0)),
                ('sleep_score', models.IntegerField(default=0)),
                ('resting_heart_rate', models.IntegerField(default=0)),
                ('max_heart_rate', models.IntegerField(default=0)),
                ('avg_heart_rate', models.IntegerField(default=0)),
                ('hrv', models.FloatField(default=0)),
                ('steps', models.IntegerField(default=0)),
                ('calories_active', models.IntegerField(default=0)),
                ('calories_total', models.IntegerField(default=0)),
                ('distance_meters', models.FloatField(default=0)),
                ('intensity_minutes', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('body_fat_percentage', models.FloatField(default=0)),
                ('bmi', models.FloatField(default=0)),
                ('stress_level', models.IntegerField(default=0)),
                ('recovery_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete')),
            ],
            options={
                'db_table': 'core_biometric_data',
                'indexes': [models.Index(fields=['-date'], name='core_biomet_date_7c9db8_idx'), models.Index(fields=['athlete', '-date'], name='core_biomet_athlete_499962_idx')],
                'unique_together': {('athlete', 'date')},
            },
        ),
    ]
