# Generated by Django 5.1.5 on 2025-02-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_corebiometricdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebiometricdata',
            name='average_respiration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='awake_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='deep_sleep_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='light_sleep_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='rem_sleep_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='total_sleep_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
