# Generated by Django 5.1.5 on 2025-02-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_datasource_athletedatasource_athlete_active_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='active_sources',
        ),
        migrations.DeleteModel(
            name='AthleteDataSource',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
