# Generated by Django 5.1.5 on 2025-02-12 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_corebiometricdata_average_respiration_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='biometricdata',
            new_name='biometric_d_date_722c6d_idx',
            old_name='core_biomet_date_511532_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricdata',
            new_name='biometric_d_athlete_c9a25d_idx',
            old_name='core_biomet_athlete_7471e2_idx',
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='average_respiration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='awake_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='deep_sleep_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='light_sleep_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='rem_sleep_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='total_sleep_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='avg_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='awake_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='calories_active',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='calories_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='deep_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='hrv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='intensity_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='light_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='max_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='recovery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='rem_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='resting_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='sleep_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='stress_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='biometricdata',
            table='biometric_data',
        ),
    ]
