# Generated by Django 5.1.5 on 2025-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_athlete_active_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_data_sources',
            field=models.JSONField(default=list, help_text='List of active data sources for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_check',
            field=models.DateTimeField(auto_now=True, help_text='Last time the data sources were checked'),
        ),
    ]
