# Generated by Django 5.1.5 on 2025-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_corebiometricdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebiometricdata',
            name='created_at',
            field=models.DateTimeField(default='2025-03-06 18:19:13.179705+00:00'),
        ),
        migrations.AlterField(
            model_name='garmincredentials',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='whoopcredentials',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
