# Generated by Django 5.1.5 on 2025-02-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_active_data_sources_user_last_source_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoopcredentials',
            name='scope',
            field=models.CharField(default='offline read:recovery read:cycles read:sleep read:workout read:profile', max_length=255),
        ),
    ]
