# Generated by Django 5.1.5 on 2025-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_corebiometricdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebiometricdata',
            name='created_at',
            field=models.DateTimeField(default='2025-03-06 18:19:30.482604+00:00'),
        ),
    ]
