# Generated by Django 5.1.5 on 2025-02-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_whoopcredentials_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebiometricdata',
            name='calories_burned',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='day_strain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='hrv_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='recovery_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='respiratory_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='skin_temp_celsius',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='sleep_consistency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='sleep_disturbances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='sleep_efficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='sleep_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='spo2_percentage',
            field=models.FloatField(default=0),
        ),
    ]
