# Generated by Django 5.1.5 on 2025-03-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_corebiometricdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebiometricdata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
