# Generated by Django 5.1.5 on 2025-03-02 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_corebiometricdata_calories_burned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corebiometricdata',
            old_name='day_strain',
            new_name='strain',
        ),
        migrations.RemoveField(
            model_name='corebiometricdata',
            name='sleep_score',
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='baseline_sleep_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='body_fat_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='first_name',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='gender',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='height_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='kilojoules',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='last_name',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='need_from_recent_nap_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='need_from_recent_strain_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='need_from_sleep_debt_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='no_data_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='sleep_cycle_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='sleep_debt_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='sleep_needed_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='sleep_performance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='total_in_bed_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='user_calibrating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corebiometricdata',
            name='weight_kg',
            field=models.IntegerField(default=0),
        ),
    ]
