# Generated by Django 5.1.5 on 2025-03-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_corebiometricdata_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corebiometricdata',
            unique_together={('athlete', 'date', 'source')},
        ),
        migrations.AddIndex(
            model_name='corebiometricdata',
            index=models.Index(fields=['athlete', 'source'], name='core_biomet_athlete_cb1373_idx'),
        ),
    ]
