# Generated by Django 5.1.5 on 2025-03-09 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_coachcode_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_permissions',
            field=models.IntegerField(default=1, help_text='Level of data access permissions (higher = more access)'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('FORWARD', 'Forward'), ('MIDFIELDER', 'Midfielder'), ('DEFENDER', 'Defender'), ('GOALKEEPER', 'Goalkeeper'), ('', 'Not Specified')], default='', help_text='Position for athletes', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_users', to='core.team'),
        ),
    ]
