# Generated by Django 5.1.5 on 2025-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_data_permissions_user_position_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='athletes_array',
            field=models.JSONField(default=list, help_text='Array of athlete IDs associated with this team, used for data syncing'),
        ),
    ]
