# Generated by Django 5.1.5 on 2025-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_team_athletes_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cached_biometric_data',
            field=models.JSONField(default=list, help_text='Cached biometric data for this team, used for data syncing'),
        ),
    ]
